var Problem2 = (function(){

	// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

	var sum = 0;
	var terms = [1, 2];
	var i = 2;
	var result;

	// Build the array of Fibonacci numbers
	while (true) {
		
		if ( i == 2 ){
			result = terms[0] + terms[1];
			terms.push(result);
		}

	 	if ( terms[i] >= 4000000 ){
	 		break;
	 	}
	 	else{
	 		result = terms[i] + terms[i - 1];
	 		terms.push(result);
	 	}
		i++;
	};

	// compute the sum of the even Fibonacci numbers
	for (var j = 0; j < terms.length; j++){
		if ( terms[j] % 2 === 0 ){
			sum += terms[j]; 
		}	
	}

	return sum;

}());